@HoteListing = http://localhost:5247

GET {{HoteListing}}/api/Hotels
Accept: application/json

###

POST  {{{{HoteListing}}}}/api/Hotels
Content-Type: application/json

{
    //Hotel
    "id": 4,
    "name": "Grand Plaza",
    "address": "123 Main St",
    "rating": 4.5
}

###
@id=1
DELETE  {{HoteListing}}/api/Hotels/{{id}}

###

GET  {{HoteListing}}/api/Hotels/{{id}}

###

PUT  {{HoteListing}}/api/Hotels/{{id}}

###